In [1]:
# a. Write a function called GetData to get the data for a network from an EXCEL file in 
# which values of p and q are given in cells A1 and B1. Then get the “arc list” starting in 
# row 2 of the file, in which each arc’s two connected nodes are in given in column A and 
# B (see the file ArcList.xlsx with the data of the network above). The arc list should be 
# returned to main program as a list of lists with element 0 being the list [p, q]. (10 points)

In [2]:
# Exercise 1. A network consists of a collection of p circles, called nodes that represent objects in 
# solving certain problems. The network also has q lines, called arcs that connect pairs of nodes to 
# express a relationship between the objects represented by the connected nodes, for example:

In [6]:
import sys
from openpyxl import load_workbook

def GetData(ws):
    p = ws.cell(row = 1, column = 1).value ### the number of nudes
    q = ws.cell(row = 1, column = 2).value ### the number of arcs
    print("There are",p,"nudes and",q,"arcs.")
    i = 1
    j = 1
    list_data = []
    while ws.cell(row = i, column = j).value != None:
            p = ws.cell(row = i, column = j).value
            q = ws.cell(row = i, column = j + 1).value
            list_data = list_data + [[p,q]]
            i = i + 1
    return list_data    
    

##### Main functions
loc = "C:\\Users\Cuiziming\Desktop\ArcList_Test.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']
Data = GetData(ws)
print(Data)
num = int(input("Please input the number of GetData that you want to know:"))
print("The result of GetData["+str(num)+"] is "+str(Data[num]))


File opened successfully!
There are 5 nudes and 4 arcs.
[[5, 4], [1, 2], [2, 3], [2, 4], [3, 4]]
Please input the number of GetData that you want to know:3
The result of GetData[3] is [2, 4]


In [16]:
# b. Write a function called Degrees that returns a list of the “degrees” of all the nodes, where 
# the degree of a node is the number of arcs coming out of that node (for the example 
# above, the degree of Node 1 is 1 and the degree of Node 3 is 2). (10 points)

In [7]:
import sys
from openpyxl import load_workbook

def Degrees(ws):
    nude_num = ws.cell(row = 1, column = 1).value
    list_data = [0 for m in range(nude_num)]
    print("Initialization of Degree List:",list_data)
    i = 2
    j = 1
    num = 0
    while ws.cell(row = i, column = j).value != None:
        while ws.cell(row = i, column = j).value != None:
            if ws.cell(row = i, column = j).value == num:
                list_data[num] = list_data[num] + 1
            else:
                num = ws.cell(row = i, column = j).value
                list_data[num] = list_data[num] + 1
            i = i + 1
        j = j + 1
        i = 2
    return list_data        

##### Main functions
loc = "C:\\Users\Cuiziming\Desktop\ArcList_Test.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']
Degree = Degrees(ws)
print("The degree of Node is",Degree)
num = int(input("Please input the number of Degree that you want to know:"))
print("The degree of Node "+str(num)+" is "+str(Degree[num]))


File opened successfully!
Initialization of Degree List: [0, 0, 0, 0, 0]
The degree of Node is [0, 1, 3, 2, 2]
Please input the number of Degree that you want to know:3
The degree of Node 3 is 2


In [42]:
# c. Write a function called DeleteNode that deletes a node from a network that is stored as an 
# arc list by performing the following operations:
# 1) Delete all of the k arcs coming out of the deleted node.
# 2) Reduce by 1 the number of all nodes greater than the number of the node being 
# deleted.
# 3) Reduce the total number of nodes by 1 and the number of arcs by k.
# For example, if you want to delete Node 3 from the network above, then you must also 
# remove the k = 2 arcs 2 – 3 and 4 – 3. Node 4 would then become Node 3 and the 
# number of nodes and arcs in the new network would be 4 and 2, so the new arc list would 
# be: [(4, 2), (1, 2), (2, 3)]. (15 points)

In [8]:
import sys
from openpyxl import load_workbook

def GetData(ws):
    p = ws.cell(row = 1, column = 1).value ### the number of nudes
    q = ws.cell(row = 1, column = 2).value ### the number of arcs
    print("There are",p,"nudes and",q,"arcs.")
    i = 1
    j = 1
    list_data = []
    while ws.cell(row = i, column = j).value != None:
            p = ws.cell(row = i, column = j).value
            q = ws.cell(row = i, column = j + 1).value
            list_data = list_data + [[p,q]]
            i = i + 1
    return list_data

def DeleteNode(List_data):
    rows = len(List_data)
    cols = len(List_data[0][:])
    Del_num = int(input("Please input the number of nude that you want to delete:"))
    ###### input number must be in (0~4)
    if Del_num < 0 or Del_num > 4:
        print("Can't delete this kind of nude!")
        return
    ########
    i = 1
    j = 0
    ### k means the number of delete arcs 
    k = 0
    ### sign means start delete
    sign = 0
    
    #####Delete list
    while i <= rows - 1:
        while j <= cols - 1 and i <= rows -1:
            if List_data[i][j] == Del_num:
                #print("!!!!!",i,j,rows-1,cols-1)
                del List_data[i]
                j = 0
                k = k + 1
                rows = rows - 1
                sign = 1
                #print("!!!!!!!!",i,j,List_data,rows-1,cols-1)
            else:    
                j = j + 1
        i = i + 1
        j = 0
    #print("the first del:",List_data)
    ##### Change List_data[0][0],List_data[0][1]
    
    List_data[0][0] = List_data[0][0] - 1
    List_data[0][1] = List_data[0][1] - k
    #print(List_data[0],List_data)
    ##### Change the number which is larger than del_num
    m = 1
    n = 0
    rows_2 = len(List_data)
    cols_2 = len(List_data[0][:])
    while m <= rows_2 - 1:
        while n <= cols_2 - 1:
            if List_data[m][n] > Del_num:
                List_data[m][n] = List_data[m][n] - 1
            n = n + 1
        m = m + 1
        n = 0   
    print("The result is:", List_data)
    return List_data            
    
    
    
##### Main functions
loc = "C:\\Users\Cuiziming\Desktop\ArcList_Test.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']
Data = GetData(ws)
print("The initial arc list is:",Data)
DeleteNode(Data)



File opened successfully!
There are 5 nudes and 4 arcs.
The initial arc list is: [[5, 4], [1, 2], [2, 3], [2, 4], [3, 4]]
Please input the number of nude that you want to delete:3
The result is: [[4, 2], [1, 2], [2, 3]]


[[4, 2], [1, 2], [2, 3]]

In [ ]:
# Exercise 2. Write the three functions in Exercise 1, but this time, the data for the network are 
# stored in an “adjacency matrix”, say A, in which Aij = 1 if i – j is an arc in the network, and 0 
# otherwise. For example, the (5 x 5) adjacency matrix for the network in Exercise 1 is given in the 
# file AdjacencyMatrix.xlsx (an empty cell indicates a value of 0 for the adjacency matrix). (Hint: 
# Use the numpy method “delete” to delete a row and column of A.) (35 points)

In [9]:
####### Function 1 named GetData: realize get data from AdjacencyMatrix.xlsx and store in Matrix 

import numpy as np
import sys
from openpyxl import load_workbook

def GetData(ws):
    i = 1
    j = 1
    ### get the rows 
    while ws.cell(row = i, column = j).value != None:
        i = i + 1
    rows = i - 2    
    ### get the cols
    i = 1 ### initialize the i
    while ws.cell(row = i, column = j).value != None:
        j = j + 1
    cols = j - 2  
    #print(rows,cols)
    #rows and cols decide what kind of (p x n) matrices that we create
    A = np.zeros((rows,cols),dtype = int) 
    # initialize the i,j
    i = 0
    j = 0
    while i <= rows - 1:
        while j <= cols - 1:
            if(ws.cell(row = i + 2, column = j + 2).value == 1):
                A[i][j] = 1
            j = j + 1
        i = i + 1
        j = 0
    print("Data from AdjacencyMatrix.xlsx have transformed in matrices:")
    print(A)
    return A

#### Main function:
loc = "C:\\Users\Cuiziming\Desktop\AdjacencyMatrix.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']

AdjacencyMatrix = GetData(ws)
### Implement an input of 2 numbers, separated by commas between each word.
#print("Please input two numbers(0~4) to represent the nudes, separated by commas between each word:")
i,j = map(int,input("Please input two numbers(0~4) to represent the nudes, separated by commas between each word:").split(','))
print("AdjacencyMatrix["+str(i)+"]["+str(j)+"] is:",AdjacencyMatrix[i][j])

#### calculate the numbe of nodes
Sum_nudes = AdjacencyMatrix.shape[0]
Sum_arcs = 0
m = 0
n = 0
Data_list = [[0,0]]
while m <= Sum_nudes - 1:
    while n <= Sum_nudes - 1:
        if(AdjacencyMatrix[m][n] == 1):
            Sum_arcs = Sum_arcs + 1
            if(m <= n):
                Data_list = Data_list + [[m,n]]
        n = n + 1
    m = m + 1
    n = 0
Sum_arcs = int(Sum_arcs / 2) 
print("Now, the number of nodes is/are",Sum_nudes)
print("And, the number of arcs is/are",Sum_arcs)
Data_list[0] = [Sum_nudes,Sum_arcs]
print("Show the result in List:")
print(Data_list)


File opened successfully!
Data from AdjacencyMatrix.xlsx have transformed in matrices:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 1]
 [0 0 1 0 1]
 [0 0 1 1 0]]
Please input two numbers(0~4) to represent the nudes, separated by commas between each word:2,3
AdjacencyMatrix[2][3] is: 1
Now, the number of nodes is/are 5
And, the number of arcs is/are 4
Show the result in List:
[[5, 4], [1, 2], [2, 3], [2, 4], [3, 4]]


In [10]:
####### Function 2 named Degrees:

import numpy as np
import sys
from openpyxl import load_workbook

def GetData(ws):
    i = 1
    j = 1
    ### get the rows 
    while ws.cell(row = i, column = j).value != None:
        i = i + 1
    rows = i - 2    
    ### get the cols
    i = 1 ### initialize the i
    while ws.cell(row = i, column = j).value != None:
        j = j + 1
    cols = j - 2  
    #print(rows,cols)
    #rows and cols decide what kind of (p x n) matrices that we create
    A = np.zeros((rows,cols),dtype = int) 
    # initialize the i,j
    i = 0
    j = 0
    while i <= rows - 1:
        while j <= cols - 1:
            if(ws.cell(row = i + 2, column = j + 2).value == 1):
                A[i][j] = 1
            j = j + 1
        i = i + 1
        j = 0
    print("Data from AdjacencyMatrix.xlsx have transformed in matrices:")
    print(A)
    return A

def Degrees(AdjacencyMatrix):
    rows = AdjacencyMatrix.shape[0]
    cols = AdjacencyMatrix.shape[1]
    i = 0
    j = 0
    
    #sum_arcs =  np.zeros((1, cols), dtype = int)
    sum_arcs = [0 for i in range(cols)]
    #print(sum_arcs)
    while i <= rows - 1:
        while j <= cols - 1:
            sum_arcs[i] = sum_arcs[i] + AdjacencyMatrix[i][j]
            j = j + 1
        i = i + 1
        j = 0
    print("All nudes'degree is",sum_arcs)
    return sum_arcs

#### Main function:
loc = "C:\\Users\Cuiziming\Desktop\AdjacencyMatrix.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']
AdjacencyMatrix = GetData(ws)
sum_arcs = Degrees(AdjacencyMatrix)
Node_num = int(input("Please input the number of nude(0~4) that you want to know its degree:"))
print("The degree of Node "+str(Node_num)+" is",sum_arcs[Node_num])

File opened successfully!
Data from AdjacencyMatrix.xlsx have transformed in matrices:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 1]
 [0 0 1 0 1]
 [0 0 1 1 0]]
All nudes'degree is [0, 1, 3, 2, 2]
Please input the number of nude(0~4) that you want to know its degree:3
The degree of Node 3 is 2


In [11]:
###### Function 3 called DeleteNode
import numpy as np
import sys
from openpyxl import load_workbook

def GetData(ws):
    i = 1
    j = 1
    ### get the rows 
    while ws.cell(row = i, column = j).value != None:
        i = i + 1
    rows = i - 2    
    ### get the cols
    i = 1 ### initialize the i
    while ws.cell(row = i, column = j).value != None:
        j = j + 1
    cols = j - 2  
    #print(rows,cols)
    #rows and cols decide what kind of (p x n) matrices that we create
    A = np.zeros((rows,cols),dtype = int) 
    # initialize the i,j
    i = 0
    j = 0
    while i <= rows - 1:
        while j <= cols - 1:
            if(ws.cell(row = i + 2, column = j + 2).value == 1):
                A[i][j] = 1
            j = j + 1
        i = i + 1
        j = 0
    print("Data from AdjacencyMatrix.xlsx have transformed in matrices:")
    print(A)
    return A

def Degrees(AdjacencyMatrix):
    rows = AdjacencyMatrix.shape[0]
    cols = AdjacencyMatrix.shape[1]
    i = 0
    j = 0
    
    #sum_arcs =  np.zeros((1, cols), dtype = int)
    sum_arcs = [0 for i in range(cols)]
    #print(sum_arcs)
    while i <= rows - 1:
        while j <= cols - 1:
            sum_arcs[i] = sum_arcs[i] + AdjacencyMatrix[i][j]
            j = j + 1
        i = i + 1
        j = 0
    print("All nudes'degree is",sum_arcs)
    return sum_arcs

def DeleteNode(AdjacencyMatrix):
    delete_nude = int(input("Please input the number of nude(0~4) that you want to delete:"))
    AdjacencyMatrix = np.delete(AdjacencyMatrix, delete_nude, axis = 0)
    AdjacencyMatrix = np.delete(AdjacencyMatrix, delete_nude, axis = 1)
    print("After deleting, the new matrix:")
    print(AdjacencyMatrix)
    return AdjacencyMatrix

#### Main function:
loc = "C:\\Users\Cuiziming\Desktop\AdjacencyMatrix.xlsx"
try:
    wb = load_workbook(loc)
    print('File opened successfully!')
except:
    sys.exit('Unable to open the file.')
ws = wb['DATA']
AdjacencyMatrix = GetData(ws)
Delete_Matrix = DeleteNode(AdjacencyMatrix)
Node_degree = Degrees(Delete_Matrix)
#### Calculate the number of nodes
Sum_nudes = len(Node_degree)
#### Calculate the number of arcs
Sum_arcs = 0
i = 0
j = 0
Data_list = [[0,0]]
while i <= len(Node_degree) - 1:
    while j <= len(Node_degree) - 1:
        if(Delete_Matrix[i][j] == 1):
            Sum_arcs = Sum_arcs + 1
            if(i <= j):
                Data_list = Data_list + [[i,j]]
        j = j + 1
    i = i + 1
    j = 0
Sum_arcs = int(Sum_arcs / 2)    
print("Now, the number of nodes is",Sum_nudes)
print("And, the number of arcs is",Sum_arcs)
Data_list[0] = [Sum_nudes,Sum_arcs]
print("Show the result in List:")
print(Data_list)

File opened successfully!
Data from AdjacencyMatrix.xlsx have transformed in matrices:
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 1]
 [0 0 1 0 1]
 [0 0 1 1 0]]
Please input the number of nude(0~4) that you want to delete:2
After deleting, the new matrix:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]
All nudes'degree is [0, 0, 1, 1]
Now, the number of nodes is 4
And, the number of arcs is 1
Show the result in List:
[[4, 1], [2, 3]]


In [53]:
# Exercise 3. Write a program to perform each of the following tasks using Numpy arrays.

In [54]:
# a. Write a function called GetAMatrix that creates a (p x n) matrix A of random real 
# numbers between –10 and 10 in the form of a numpy array, where p < n are both 
# obtained from the user. (5 points)

In [12]:
import numpy as np
import sys
import random

def GetAMatrix(p,n):
    A = np.random.uniform(-10,10,size = (p,n))
    return A

#### Main function 
p = int(input("Please input the number of p:"))
n = int(input("Please input the number of n:"))
while p >= n:
    print("Your p >= n!!!!!!!!! Please re-enter p,n,and keep p < n!")
    p = int(input("Please input the number of p:"))
    n = int(input("Please input the number of n:"))
A = GetAMatrix(p,n)
print("The matrix of A is:")
print(A)

Please input the number of p:3
Please input the number of n:5
The matrix of A is:
[[-5.08430666 -7.87264825 -8.85123425  5.76440406  2.16729367]
 [-8.51018829  2.09562874 -9.45558816  3.16327466 -8.5789847 ]
 [-0.93413463 -6.24101832  1.35449578  0.87486815  7.9356831 ]]


In [76]:
# b. Write a function called GetBasics that, given the integers p and n, returns a list, say 
# basics, of p different randomly-chosen values from 0, 1, …, n – 1 with the remaining 
# values in 0, 1, …, n – 1 being stored in the list nonbasics. Do this by starting with
# basics = [ ] and nonbaiscs = [0, 1, …, n – 1]. Then sequentially use the “pop” method to 
# move a random element of nonbasics to basics exactly p times. (5 points)

In [13]:
import numpy as np
import sys
import random

def GetBasics(p,n):
    nonbasics = [i for i in range(n)]
    basics = []
    ####### randomly-chosen values from 0, 1, …, n – 1
    while p != 0:
        random_num = random.randint(0, n-1)
        print("At present, nonbasics is")
        print(nonbasics)
        print("Pop the number of",random_num,"which is",nonbasics[random_num])
        basics = basics + [nonbasics[random_num]]
        print("At present, basics is")
        print(basics)
        nonbasics.pop(random_num)
        n = n - 1
        p = p - 1
    print("######################################################")
    print("Finally, the result of basics is:")
    print(basics)
    print("Finally, the result of nonbasics is:")
    print(nonbasics)
    return basics,nonbasics
##### Main function:
p = int(input("Please input the number of p:"))
n = int(input("Please input the number of n:"))
while p >= n:
    print("Your p >= n!!!!!!!!! Please re-enter p,n,and keep p < n!")
    p = int(input("Please input the number of p:"))
    n = int(input("Please input the number of n:"))
GetBasics(p,n)



Please input the number of p:3
Please input the number of n:5
At present, nonbasics is
[0, 1, 2, 3, 4]
Pop the number of 1 which is 1
At present, basics is
[1]
At present, nonbasics is
[0, 2, 3, 4]
Pop the number of 3 which is 4
At present, basics is
[1, 4]
At present, nonbasics is
[0, 2, 3]
Pop the number of 2 which is 3
At present, basics is
[1, 4, 3]
######################################################
Finally, the result of basics is:
[1, 4, 3]
Finally, the result of nonbasics is:
[0, 2]


([1, 4, 3], [0, 2])

In [94]:
# c. Given the lists basics and nonbasics from part (b), write a function called GetBandN that 
# returns the submatrix B consisting of the columns of A indexed by the list basics together 
# with the submatrix N consisting of the remaining columns of A. For example, if n = 5 and 
# the basics are [2, 4] and the nonbasics are [1, 5, 3], then B consists of columns 2 and 4 of 
# A while N consists of columns 1, 5, and 3 of A. (5 points)

In [14]:
import numpy as np
import sys
import random

def GetAMatrix(p,n):
    A = np.random.uniform(-10,10,size = (p,n))
    return A

def GetBasics(p,n):
    nonbasics = [i for i in range(n)]
    basics = []
    ####### randomly-chosen values from 0, 1, …, n – 1
    print("######################################################")
    while p != 0:
        random_num = random.randint(0, n-1)
        print("At present, nonbasics is")
        print(nonbasics)
        print("Pop the number of",random_num,"which is",nonbasics[random_num])
        basics = basics + [nonbasics[random_num]]
        print("At present, basics is")
        print(basics)
        nonbasics.pop(random_num)
        n = n - 1
        p = p - 1
    print("######################################################")
    print("Finally, the result of basics is:")
    print(basics)
    print("Finally, the result of nonbasics is:")
    print(nonbasics)
    print("######################################################")
    return basics,nonbasics

def GetBandN(A,basics,nonbasics):
    B = A[:,basics]
    N = A[:,nonbasics]
    return B,N
    
#### Main function 
p = int(input("Please input the number of p:"))
n = int(input("Please input the number of n:"))
while p >= n:
    print("Your p >= n!!!!!!!!! Please re-enter p,n,and keep p < n!")
    p = int(input("Please input the number of p:"))
    n = int(input("Please input the number of n:"))
A = GetAMatrix(p,n)
print("The matrix of A is:")
print(A)
basics,nonbasics = GetBasics(p,n)
B,N = GetBandN(A,basics,nonbasics)
print("B is:")
print(B)
print("N is:")
print(N)


Please input the number of p:5
Please input the number of n:6
The matrix of A is:
[[-7.76360947  1.44677643 -6.63074701 -8.82224762 -3.5465028   7.16685797]
 [ 5.10323803  3.94335711  9.53539937  2.02538762  3.20845199  0.15451609]
 [ 6.18134174 -3.50614251  4.80410305 -4.21790957 -6.23427265 -0.82748   ]
 [ 8.12801884  9.49231744 -1.89131498 -7.5573092  -0.55063345 -7.1320547 ]
 [-9.26856064 -2.15542089 -7.19232397 -9.70179278 -6.30422224  5.04724191]]
######################################################
At present, nonbasics is
[0, 1, 2, 3, 4, 5]
Pop the number of 0 which is 0
At present, basics is
[0]
At present, nonbasics is
[1, 2, 3, 4, 5]
Pop the number of 3 which is 4
At present, basics is
[0, 4]
At present, nonbasics is
[1, 2, 3, 5]
Pop the number of 1 which is 2
At present, basics is
[0, 4, 2]
At present, nonbasics is
[1, 3, 5]
Pop the number of 0 which is 1
At present, basics is
[0, 4, 2, 1]
At present, nonbasics is
[3, 5]
Pop the number of 1 which is 5
At present, basics i

In [ ]:
# d. Write a function called inverse that determines whether the B matrix has an inverse and, 
# if so, returns that inverse matrix. The function should also return a Boolean variable 
# indicating whether the B matrix has an inverse (True) or not (False). (Hint: Use the 
# subpackage linalg of numpy.) (5 points.)

In [15]:
import numpy as np
import sys
import random

def GetAMatrix(p,n):
    A = np.random.uniform(-10,10,size = (p,n))
    return A

def GetBasics(p,n):
    nonbasics = [i for i in range(n)]
    basics = []
    ####### randomly-chosen values from 0, 1, …, n – 1
    print("######################################################")
    while p != 0:
        random_num = random.randint(0, n-1)
        print("At present, nonbasics is")
        print(nonbasics)
        print("Pop the number of",random_num,"which is",nonbasics[random_num])
        basics = basics + [nonbasics[random_num]]
        print("At present, basics is")
        print(basics)
        nonbasics.pop(random_num)
        n = n - 1
        p = p - 1
    print("######################################################")
    print("Finally, the result of basics is:")
    print(basics)
    print("Finally, the result of nonbasics is:")
    print(nonbasics)
    print("######################################################")
    return basics,nonbasics

def GetBandN(A,basics,nonbasics):
    B = A[:,basics]
    N = A[:,nonbasics]
    return B,N

def inverse(B):
    Result_List = []
    try:
        inverse_B = np.linalg.inv(B)
        Result_List = Result_List + [True,inverse_B]
        return Result_List
    except:
        Result_List = Result_List + [False]
        return Result_List
        
#### Main function 
p = int(input("Please input the number of p:"))
n = int(input("Please input the number of n:"))
while p >= n:
    print("Your p >= n!!!!!!!!! Please re-enter p,n,and keep p < n!")
    p = int(input("Please input the number of p:"))
    n = int(input("Please input the number of n:"))
A = GetAMatrix(p,n)
print("The matrix of A is:")
print(A)
basics,nonbasics = GetBasics(p,n)
B,N = GetBandN(A,basics,nonbasics)
print("B is:")
print(B)
inverse_B = inverse(B)
print("Inverse of B is:")
if(inverse_B[0] == True):
    print(inverse_B[1])
    print(inverse_B[0])
else:    
    print(inverse_B[0])
    print("B does't have inverse matrix!!!!")


Please input the number of p:5
Please input the number of n:9
The matrix of A is:
[[-9.85391787  2.8060329   4.0485738  -5.16535787  3.53148328  8.66997153
  -1.56772986  2.58117214 -5.42752057]
 [-5.31380895 -2.03915399  8.06253341  8.26659591  0.84695297  9.16007171
  -1.32343447 -3.55907187  4.47502501]
 [ 7.80984583  2.81166399  5.60451891 -4.47149777 -6.57562971 -3.61711842
  -5.51853321  9.08073441  3.13608557]
 [-4.81467815 -8.22408439 -4.23850457 -4.93693198  3.37638968 -4.88388686
   8.32162195 -9.32817717 -1.77113813]
 [-6.39058819 -5.88534616  7.11998378 -0.74323745 -3.03275715 -7.33572332
   2.13823527  4.16403246  9.17560228]]
######################################################
At present, nonbasics is
[0, 1, 2, 3, 4, 5, 6, 7, 8]
Pop the number of 2 which is 2
At present, basics is
[2]
At present, nonbasics is
[0, 1, 3, 4, 5, 6, 7, 8]
Pop the number of 1 which is 1
At present, basics is
[2, 1]
At present, nonbasics is
[0, 3, 4, 5, 6, 7, 8]
Pop the number of 6 which is 8